# Pandemic Suite Configuration File		

title = 'Example of a SEIR Configuration File'
date = '2021-04-20'
user = 'Samuel'

[model]
	name = "Example simulation"
	id = ''
	model = 'SEIRMETA'
	compartments  = ['S','E','I','R']
	

[data]
	# Real data will set initial conditions and will be available to be plotted and to calculate errors	
	datafile = false # File path for importing data from file 
	importdata = false # Import data from external source

	# parameters to use when importing from external sources 
	initdate = ''
	country = ''
	state = ''
	county = ''#'13101'
	healthservice = ''
	loc_name= '' # optional
	geo_topology = 'meta' # Populations topology
	

[parameters]
	[parameters.static]
	t_init = 0 # Initial day
	t_end = 500 # Final day	
	
	# Saturation dynamic
	k_I = 0
	k_R = 0

	#popfraction = [1,1,1] # Fraction of the total population that take part on the dynamic at the beginning

	mu = [1.5,1.5,1.5] # E(0) = mu*I(0)	
	# Subreport
	pI_det = 1
	
	[parameters.dynamic]
	beta = [0.1,0.1,0.1]
	alpha = [1,1,1]

	# -------------------------- #
	#   Transition Parameters    # 
	# -------------------------- #	
	# Transition time between exposed and infectious
    tE_I = 5.0 # 1/sigma
	# Transition time between infectious and removed
    tI_R = 10.0 # 1/gamma	
	# Average Immunity loss rate (1/time)
	rR_S = 0 
	
[initialconditions]
	# total population in area
	population = [100000,100000,100000]

	# Recovered	
	R = [0,0,0]

	# Infected	
	# Active Infected
	I = [100,200,300]
	# New daily Infected
	I_d = [10,20,30]	
	# Accumulated Infected	
	I_ac = [100,200,300]

	# Leave E and E_d as false for using mu
	E = false
	E_d = false
