# Pandemic Suite Configuration File		

title = 'Example of a SEIR Configuration File'
date = '2021-04-20'
user = 'Samuel'

[model]
	name = "SEIR"
	compartments  = ['S','E','I','R'] # Nombres de los estados
	#variables  = ['S','S_d','S_ac','E','E_d','E_ac','I','I_d','I_ac','R','R_d','R_ac']
	

[data]
	# Real data will set initial conditions and will be available to be plotted and to calculate errors	
	datafile = false # File path for importing data from file 
	importdata = false # Import data from external source
	# parameters to use when importanting from external sources 
	initdate = '2020-12-18'
	country = 'Chile'
	state = '13'
	county = ''#'13101'
	healthservice = ''
	loc_name= 'Santiago' # optional 


[parameters]
	[parameters.static]
	t_init = 0 # Initial day
	t_end = 500 # Final day
	timestep = 0.01 # Timestep for solver
	
	k_I = 0
	k_R = 0

	seroprevfactor = 1
	expinfection = 0

	mu = 0.298
	
	# Subreport
	pI_det = 1		
	
	[parameters.dynamic]
	beta = 0.15
	alpha = '{"function":"Events","values":[0.45,0.85],"days":[[0,100],[100,500]]}'  # Refer to function constructor library
	
	# External flux rates over time 
	S_f = 0
	E_f = 0
	I_f = 0
	R_f = 0	
	
	# -------------------------- #
	#   Transition Parameters    # 
	# -------------------------- #	
        tE_I = 5.0 # 1/sigma
        tI_R = 10.0 # 1/gamma
	
	eta = 0 # Immunity loss rate
[initialconditions]
	# total population in area
	population = 1000000

	# Recovered	
	R = 5000

	# Infected
	# Note: In case real and detected values are >0, real value will be used
	# Active Infected
	I = 0	# Real Infected
	I_det = 6000	# Detected Infected

	# New daily Infected
	I_d = 0
	I_d_det = 3000	
	
	# Accumulated Infected	
	I_ac = 0
	I_ac_det = 15000

	E = false
	E_d = false
	
[ephemeris]
	# In case we work with real data, this will help to locate important dates in our plots
	newyear = '2020-12-31'
	fiestaspatrias = '2020-09-18'




