# Pandemic Suite Configuration File		

title = 'Example of a SEIR Configuration File'
date = '2021-04-20'
user = 'Samuel'

[model]
	name = "Example simulation"
	id = ''
	model = 'SEIRMETA'
	compartments  = ['S','E','I','R'] 
	
	# Differential Equations
	EDOs = true
	# Rule based modeling
	RBM = false
	RBM_N = 1

[data]
	# Real data will set initial conditions and will be available to be plotted and to calculate errors	
	datafile = false # File path for importing data from file 
	importdata = false # Import data from external source

	# parameters to use when importing from external sources 
	initdate = ''
	country = ''
	state = ''
	county = ''#'13101'
	healthservice = ''
	loc_name= '' # optional
	geo_topology = 'meta' # New parameter indicating if it's mono or meta populations

[parameters]
	[parameters.static]
	t_init = 0
	t_end = 500 # Final day	
	
	# Saturation dynamic
	k_I = 0
	k_R = 0

	#popfraction = [1,1,1] # Fraction of the total population that take part on the dynamic at the beginning

	mu = [1.0,0.8,1.2] # E(0) = mu*I(0)
	
	# Subreport
	pI_det = 1
	
	[parameters.dynamic]
	beta = [0.2,0.15,0.125]
	alpha = [1,1,1]

	#Phi = false
	
	
	# -------------------------- #
	#   Transition Parameters    # 
	# -------------------------- #	
	# Transition time between exposed and infectious
        tE_I = 5.0 # 1/sigma
	# Transition time between infectious and removed
        tI_R = 10.0 # 1/gamma
	
	# Average Immunity loss rate (1/time)
	rR_S = 0 
	
[initialconditions]
	# total population in area
	population = [100000,200000,150000]

	# Recovered	
	R = [5000,10000,7500]

	# Infected	
	# Active Infected
	I = [1000,0,1500]
	# New daily Infected
	I_d = [100,0,150]	
	# Accumulated Infected	
	I_ac = [4500,9000,6500]

	# Leave E and E_d as false for using mu
	#E = false
	#E_d = false
