# Pandemic Suite Configuration File		

title = "Example of a SEIRHVD Configuration File"
date = '2021-03-01'

[model]
	name = "SEIRHVD"
	compartments  = ['S','E','I','R','H','V','D'] # Nombres de los estados
	variables  = ['S','S_d','S_ac','E','E_d','E_ac','I','I_ac','R','H','V','D']
	

[parameters]
	tsim = 500 # simulation days
	
	beta = 0.15
	mu = 0.298
	k = 0
	k_I = 0
	k_R = 0
	seroprevfactor = 1
	expinfection = 0
	
	alpha = '{"function":"Events","values":[0.45,0.85],"days":[[0,100],[100,500]]}'  # Refer to function constructor library
	
	chi = 0
	
	# -------------------------- #
	#   Transition Parameters    # 
	# -------------------------- #
	
	# Transition from exposed to Asymptomatic Infected
        pE_Ias = 0.4  
        tE_Ias = 5.0

	# Transition from exposed to  Mild Infected
        pE_Imi = 0.55 
        tE_Imi = 5.0

	# Transition from exposed to  Critical Infected
        pE_Icr = 0.01666 
        tE_Icr = 3.0

	# Transition from exposed to  Serious Infected
        pE_Ise = 0.03334 
        tE_Ise = 3.0

	# Transition from Asymptomatic Infected to Recovered
        pIas_R = 1.0   
        tIas_R = 10.0

	# Transition from Mild Infected to Recovered
        pImi_R = 1.0  
        tImi_R = 15.0

	# Transition from Serious Infected to Serious Hospitalized (When Hospital capacity is not saturated)
        pIse_Hse = 1.0 
        tIse_Hse = 3.0 

	# Transition from Serious Infected to Death (When Hospital capacity is saturated)
        pIse_D = 1.0  
        tIse_D = 3.0         

	# Transition from Critical Infected to Ventilator (When Ventilators capacity is not saturated)
        pIcr_V = 1.0  
        tIcr_V = 3.0 

	# Transition from Serious Infected to Death (When Ventilators capacity is saturated)
        pIcr_D = 1.0  
        tIcr_D = 3.0         

	# Transition from Serious Hospitalized to Recovered
        pHse_R = 0.97 
        tHse_R = 11.0

	# Transition from Serious Hospitalized to Ventilators (When Ventilators capacity is not saturated)
        pHse_V = 0.03 
        tHse_V = 3.0

	# Transition from Serious Hospitalized to Death (When Ventilators capacity is saturated)
        pHse_D = 0.03 
        tHse_D = 3.0        

	# Transition from Ventilators to Hospital Recovery (Hout)
        pV_Hout = 0.5   
        tV_Hout = 15.0

	# Transition from Ventilators to Death
        pV_D = 0.5 
        tV_D = 15.0

	# Transition from Hospital Recovery (Hout) to Recovered
        pHout_R = 1.0 
        tHout_R = 4.0

	# Transition from Dead to buried
        pD_B = 1.0 
        tD_B = 1.0 

	# Contagion by deads rate
        betaD = 0 
        # Recovered Immunity loss
        eta = 0.0  

	# Subreport
	pImi_det = 0.4
	pIas_det = 0.1
	pIse_det = 1
	pIcr_det = 1
	
	
	
[initialconditions]
	overwrite_ic = true # In case we use realdata we can overwrite the IC with this values

	population = 1000000
	B = 1000
	D = 50
	R = 5000

	# Active Infected
	I = 0	# Real Infected
	I_det = 6000	# Detected Infected

	# New daily Infected
	I_d = 0
	I_d_det = 3000	
	# Accumulated Infected	
	I_ac = 0
	I_ac_det = 15000
	
	# Hospitalization 
	# Capacity
	H_cap = 3000
	V_cap = 2000

	# Use
	H = 1500
	V = 1000
	
	# Misc
	name = ''	
	country = ''
	state = ''	
	healtservice = ''
	realdata = false
	importdata = false
	datafile = false			
	
	#initdate = '2020-12-15'
	
[realdata]
	# Real data will set initial conditions and will be available to be plotted and to calculate errors
	realdata = true
	importdata = true
	datafile = false
	initdate = '2020-12-15'
	country = 'Chile'
	state = '13101'	
	healtservice = false
	# The next one is optional
	name = 'Santiago'
	
[ephemeris]
	# In case we work with real data, this will help to locate important dates in our plots
	newyear = '2020-12-31'
	fiestaspatrias = '2020-09-18'




