# Pandemic Suite Configuration File		

title = 'Example of a SEIRHVD Configuration File'
date = '2021-06-01'
user = ''

[model]
	name = "SEIR-SEIRHVD comparison"
	model = "SEIRHVD"	
	compartments  = ['S','S_v','E','E_v','Im','Icr','Iv','R','H','D'] # Nombres de los estados
	
[data]
	# Real data will set initial conditions and will be available to be plotted and to calculate errors	
	datafile = false # File path for importing data from file 
	importdata = false # Import data from external source

	# parameters to use when importing from external sources 
	initdate = ''
	country = ''
	state = ''
	county = ''#'13101'
	loc_name= '' # optional 
	
[parameters]
	[parameters.static]
	t_init = 0 # Initial day
	t_end = 500 # Final day
	
	# Saturation dynamic
	k_I = 0
	k_R = 0

	popfraction = 1 # Fraction of the total population that take part on the dynamic at the beginning
	populationfraction = 1

	mu = 0.5 # E(0) = mu*I(0)
	
	
	[parameters.dynamic]
		
	# Contagion and movility
	alpha = 1
	beta = 0.2
	beta_v = 0.05
	
	# Vaccination
	vac_d = 0 # Vaccines per day
	vac_eff = 0.7 # Vaccine effectivity
	
	# External flux rates over time 
	S_f = 0
	Sv_f = 0
	E_f = 0
	Ev_f = 0
	Iv_f = 0
	Im_f = 0
	Icr_f = 0
	H_f = 0
	D_f = 0 
	R_f = 0	


	# -------------------------- #
	#   Transition Parameters    # 
	# -------------------------- #
	# Exposed
	pE_Im = 1.0
	tE_Im = 5.0 
	pE_Icr = 0.0
	tE_Icr = 3.0 

	# Vaccinated exposed
	tEv_Iv = 3.0 

	# Infectious (asymptomatic + mild + severe)
        tIm_R = 10.0 
	
	# Infectious (critical)
        tIcr_H = 7.0
    
	# Infectious (vaccinated)
        pIv_R = 0.95
        tIv_R = 12.0 

        pIv_H = 0.0
        tIv_H = 7.0
        
        # Hospitalized (IMV)
        pH_R = 0.7
        tH_R = 11
        
        pH_D = 0.3
        tH_D = 11
	
	# Immunity loss 
	pR_S = 0 # probability
	tR_S = 90 # time
	
	# Subreport: Detected infected are calculated from the real infected given in the IC
	pIcr_det = 1	
	pIm_det = 1
	pIv_det = 1
	pI_det = 1	

	
	
[initialconditions]

	population = 1000000
	Sv = 0
	
	# Non vaccinated infected
	I = 6000 # Active Infected
	I_d = 3000 # New daily Infected
	I_ac = 15000 # Accumulated Infected	

	# Vaccinated infected: If false they will be calculated using the vaccinated proportion of susceptibles
	Iv = false
	Iv_d = false
	Iv_ac = false
	
	# Hospitalization 
	H_cap = 7000 # Capacity
	H = 0 # Use
	H_d = 0 # Use
	
	# Deaths
	D = 0
	D_d = 0

	# Recovered
	R = 5000

	# Comment E and E_d for using mu
	#E = 500
	#E_d = 0
	#Ev = 0
	#Ev_d = 0	



